# Generated by Django 2.2.6 on 2019-11-12 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_duration_rectangle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('qid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('choices', models.CharField(blank=True, max_length=50)),
                ('useTime', models.IntegerField(default=40)),
            ],
        ),
        migrations.AddField(
            model_name='duration',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Username'),
        ),
        migrations.AddField(
            model_name='rectangle',
            name='username',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Username'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('x1', models.FloatField(blank=True, null=True)),
                ('y1', models.FloatField(blank=True, null=True)),
                ('x2', models.FloatField(blank=True, null=True)),
                ('y2', models.FloatField(blank=True, null=True)),
                ('consumingtime', models.FloatField(default=0)),
                ('answer', models.CharField(blank=True, max_length=50, null=True)),
                ('qid', models.IntegerField(max_length=11)),
                ('username', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Username')),
            ],
        ),
    ]
