# Generated by Django 2.2.6 on 2019-11-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191112_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='qid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backend.Questions'),
        ),
    ]
