# Generated by Django 2.2.6 on 2019-11-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20191112_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='choices',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
