# Generated by Django 2.2.6 on 2019-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20191113_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='background',
            field=models.IntegerField(default=0),
        ),
    ]
