# Generated by Django 2.2.6 on 2019-11-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_questions_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='TestType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='questions',
            name='TestType',
            field=models.IntegerField(default=0),
        ),
    ]
