# Generated by Django 2.2.6 on 2019-11-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20191127_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='TestType',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='TestType',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='choices',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
