# Generated by Django 2.2.6 on 2019-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20191127_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='qid',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
