# Generated by Django 2.2.6 on 2019-11-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20191127_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('background', models.TextField()),
            ],
        ),
    ]
