# Generated by Django 2.2.6 on 2019-11-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='background',
            field=models.IntegerField(default=1),
        ),
    ]
