# Generated by Django 2.2.6 on 2019-12-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_username_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='label',
            field=models.TextField(blank=True, null=True),
        ),
    ]
