# Generated by Django 2.2.6 on 2019-12-10 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_background_graphname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='useTime',
        ),
    ]
