# Generated by Django 2.2.6 on 2019-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_questions_usetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questionImg',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
