# Generated by Django 2.2.6 on 2019-12-20 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_questions_questionimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='TestType',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='qid',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Questions'),
        ),
    ]
