# Generated by Django 2.2.6 on 2019-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20191220_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rectangle',
            name='duration',
        ),
        migrations.AddField(
            model_name='duration',
            name='TestType',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='duration',
            name='qid',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
